name: Test and Build Back

on: 
  push:
    branches: [ main ]

jobs: 
    test:   
      runs-on: ubuntu-latest
      steps: 
      - working-directory: ./api;
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run test
      - run: npm run build
      - run: ls dist
